- safebox/src/androidTest/java/com/harrytmthy/safebox/storage/SafeBoxBlobStoreTest.kt
- safebox/src/main/java/com/harrytmthy/safebox/SafeBox.kt
- safebox/src/main/java/com/harrytmthy/safebox/registry/SafeBoxBlobFileRegistry.kt
- safebox/src/main/java/com/harrytmthy/safebox/state/SafeBoxGlobalStateObserver.kt
- safebox/src/main/java/com/harrytmthy/safebox/state/SafeBoxState.kt
- safebox/src/main/java/com/harrytmthy/safebox/storage/SafeBoxBlobStore.kt
- safebox/src/test/java/com/harrytmthy/safebox/state/SafeBoxGlobalStateObserverTest.kt
This update introduces:
- ✅ `SafeBoxGlobalStateObserver` for global state tracking (`STARTING`, `WRITING`, `IDLE`, `CLOSED`)
- ✅ `closeWhenIdle()` method to ensure file is closed only when all pending writes have completed
This improves lifecycle safety in non-singleton environments (e.g. ViewModel-scoped SafeBox).
- Added a new `STARTING` state to differentiate the initial load vs uninitialized state (null).
- `SafeBoxBlobStore` now tracks a `MutableStateFlow` write counter
- `SafeBox.closeWhenIdle()` delegates safely using `safeBoxScope.launch`
- Global observer holds and emits latest state on subscription
Closes part of #12 (will be completed in global state listener PR)
> feat(state): Add SafeBoxGlobalStateObserver and closeWhenIdle support

- .github/workflows/ci.yml
- .github/workflows/publish.yml
This PR updates the `publish.yml` workflow to fix the GPG key and secrets injection issue by:
- Writing secrets directly into `~/.gradle/gradle.properties`
- Ensuring proper permissions and decoding for the GPG secret key ring
- Retaining both `workflow_dispatch` and tag-based triggers for flexibility
- Run manually via `workflow_dispatch` on this branch
- Confirm that `publishToMavenCentral` completes successfully
> fix(pipeline): Verify GPG and secret injection in publish workflow

- safebox/src/main/java/com/harrytmthy/safebox/SafeBox.kt
- safebox/src/main/java/com/harrytmthy/safebox/cryptography/ChaCha20CipherProvider.kt
- safebox/src/main/java/com/harrytmthy/safebox/cryptography/CipherProvider.kt
- safebox/src/main/java/com/harrytmthy/safebox/keystore/KeyProvider.kt
- safebox/src/main/java/com/harrytmthy/safebox/keystore/SafeSecretKey.kt
- safebox/src/main/java/com/harrytmthy/safebox/keystore/SecureRandomKeyProvider.kt
This PR introduces XOR-based in-memory masking to `SafeSecretKey`, strengthening the protection of the Data Encryption Key (DEK) held in native memory.
Previously, the raw DEK was stored directly in a `DirectByteBuffer`, which avoided heap leaks but still exposed the unmasked key to memory inspection tools. This posed a risk in rooted or compromised environments where attackers could scrape native memory for sensitive material.
- `SafeSecretKey` now takes an additional `mask: ByteArray` parameter.
- On construction, the key is XOR-ed with the mask and stored as a **masked DEK**.
- The mask is derived from `SHA-256(encryptedDEK)`, ensuring it's:
- Deterministic across process restarts
- Never stored on disk
- Unique per-encrypted DEK
- On `getEncoded()`, the masked key is XOR-ed again with …
> feat(keystore): Add XOR based masking to SafeSecretKey for in-memory protection

- safebox/src/main/java/com/harrytmthy/safebox/keystore/SafeSecretKey.kt
- safebox/src/main/java/com/harrytmthy/safebox/keystore/SecureRandomKeyProvider.kt
This PR enables **concurrent access** to key material in both `SafeSecretKey` and `SecureRandomKeyProvider`, aligning with the goals of #26. While both classes were technically thread-safe via synchronized blocks, they did not scale well in concurrent environments, blocking all threads during common operations like `getOrCreateKey()` or `getEncoded()`.
---
- Replaces `decryptedKey` with an `AtomicReference<SecretKey>`.
- Moves the early `get()` check outside the synchronized block.
- Rechecks the atomic value inside to avoid duplicate construction.
- `lastCopy` is now an `AtomicReference<ByteArray>`.
- The XOR-masked value is now unmasked before being stored in `lastCopy` (fix for Issue #23).
- Shrinks the synchronized scope in `getEncoded()` and reattempts the early return inside the …
> refactor(keystore): Enable concurrent access for SafeSecretKey and SecureRandomKeyProvider

- safebox/src/main/java/com/harrytmthy/safebox/concurrent/SafeBoxExecutor.kt
- safebox/src/main/java/com/harrytmthy/safebox/cryptography/ChaCha20CipherProvider.kt
- safebox/src/main/java/com/harrytmthy/safebox/cryptography/CipherPool.kt
- safebox/src/main/java/com/harrytmthy/safebox/cryptography/SingletonCipherPoolProvider.kt
- safebox/src/test/java/com/harrytmthy/safebox/cryptography/CipherPoolTest.kt
This PR introduces a new `CipherPool` class to support concurrent encryption and decryption in thread-safe SafeBox components, particularly for ChaCha20-based operations.
While previous versions used synchronized access to a single `Cipher` instance, this approach blocks multiple readers and bottlenecks under load. The new pooling system allows safe parallel access across threads while managing lifecycle and memory limits.
Key Design Decisions:
- Max pool size capped at 64
- Load factor controls early expansion before saturation
- Background expansion is handled by `SafeBoxExecutor` to avoid blocking active threads
- Consider LRU-style trimming to release idle Ciphers
- Expand `SafeBoxExecutor` into configurable thread pools if needed
---
Closes #25
> feat(crypto): Add CipherPool with SafeBoxExecutor to handle cryptographic concurrency

- safebox/src/main/java/com/harrytmthy/safebox/cryptography/ChaCha20CipherProvider.kt
- safebox/src/main/java/com/harrytmthy/safebox/cryptography/CipherPool.kt
- safebox/src/main/java/com/harrytmthy/safebox/cryptography/SingletonCipherPoolProvider.kt
This PR refactors how SafeBox integrates with BouncyCastleProvider to avoid global, unsafe modifications.
- **CipherPool** now accepts a `getCipherInstance` lambda to allow on-demand and fallback-safe instantiation.
- `SingletonCipherPoolProvider` now gracefully injects BouncyCastleProvider **only if missing**, inside a `try-catch`.
- This ensures no premature provider replacement and better compatibility with host apps or other libraries.
---
Closes #1
> refactor(crypto): Change BouncyCastleProvider init behavior

- .github/FUNDING.yml
- README.md
Now that SafeBox has been officially accepted into the **GitHub Sponsors** program, it's time to publicly show our support button on the repository. This allows users and developers who find SafeBox valuable to contribute toward its continued development, maintenance, and upcoming improvements.
> chore: Enable GitHub Sponsors button

- README.md
This PR adds project metadata badges to the top of the README for greater visibility into:
- CI build status
- Current release version (including pre-releases)
- Project license (MIT)
The badges are horizontally aligned beneath the project title for a cleaner layout.
---
Closes #39
> docs: Add Build, License, and Version badges

- CHANGELOG.md
- README.md
- safebox/build.gradle.kts
This PR finalizes the `v1.1.0` release of SafeBox, delivering major upgrades in lifecycle coordination, cryptographic safety, and multi-threaded performance.
---
- **SafeBoxStateManager**: Tracks internal states (`STARTING`, `WRITING`, `IDLE`, `CLOSED`) to ensure deterministic transitions even under concurrent writes. Prevents invalid state emissions after closure. ([#17](https://github.com/harrytmthy-dev/safebox/issues/17))
- **Global and Per-instance Observability**: 
- `SafeBoxGlobalStateObserver` monitors file-level state transitions.  
- `SafeBoxStateListener` allows per-instance state tracking.  
([#12](https://github.com/harrytmthy-dev/safebox/issues/12))
- **XOR-based In-Memory Masking**: `SafeSecretKey` is now XOR-masked using a SHA-256 mask to prevent raw DEK exposure in memory. …
> release: v1.1.0 with improved state management, security, and concurrency

- .github/CODEOWNERS
- .github/FUNDING.yml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- docs/MIGRATION.md
- gradle/libs.versions.toml
- safebox/build.gradle.kts
Deprecates the old `io.github.harrytmthy-dev` namespace in the README and introduces a clear notice to guide users toward the new canonical Maven group: `io.github.harrytmthy`.
- Replaced all "harrytmthy-dev" with "harrytmthy".
- Added a warning notice under the `## Installation` section.
Closes #45
> refactor: Deprecate harrytmthy-dev namespace

- .github/workflows/ci.yml
This PR enables Gradle caching in the SafeBox CI pipeline to reduce build times and improve overall workflow efficiency. It adds a `Cache Gradle` step in both the `build` and `instrumented-test` jobs, caching `~/.gradle/caches` and `~/.gradle/wrapper`, using the `gradle.lockfile` hash for precise cache invalidation.
- Added `actions/cache@v4` before `setup-gradle` in both CI jobs.
- Used `gradle-${{ runner.os }}-${{ hashFiles('**/gradle.lockfile') }}` as the cache key.
Closes #47
> feat(pipeline): Enable Gradle caching to improve CI performance

- safebox/src/androidTest/java/com/harrytmthy/safebox/SafeBoxTest.kt
- safebox/src/androidTest/java/com/harrytmthy/safebox/storage/SafeBoxBlobStoreTest.kt
- safebox/src/main/java/com/harrytmthy/safebox/SafeBox.kt
- safebox/src/main/java/com/harrytmthy/safebox/storage/SafeBoxBlobStore.kt
This PR resolves Issue #54 by realigning `apply()` behavior with EncryptedSharedPreferences (ESP), ensuring `getXxx()` calls return the expected values immediately after `.apply()` is invoked, even before disk writes complete.
This lays the foundation for performance enhancements to be explored in #55.
- **Moved encrypted entry map** (`Map<Bytes, ByteArray>`) from `SafeBoxBlobStore` to `SafeBox`, allowing immediate in-memory updates without waiting for disk writes.
- `getXxx(...)`, `contains(...)`, and `getAll()` now access a dedicated in-memory `entries` map in `SafeBox`, mirroring ESP behavior.
- Disk persistence via `SafeBoxBlobStore` is now fully decoupled from in-memory access, triggered only during `commit()` or `apply()`.
- Introduced `SafeBoxBlobStore.loadPersistedEntries()` to be …
> fix: Decouple encrypted entry map from blob store

- safebox/src/androidTest/java/com/harrytmthy/safebox/SafeBoxTest.kt
- safebox/src/main/java/com/harrytmthy/safebox/SafeBox.kt
- safebox/src/main/java/com/harrytmthy/safebox/state/SafeBoxStateManager.kt
Fixes a rare but critical issue where overlapping `.apply()` and `.commit()` operations on the same SafeBox instance could cause data corruption or `AEADBadTagException`. The root cause was concurrent writes to the underlying blob store, especially when `commit()` arrived before a prior `apply()` had finished persisting to disk.
This patch introduces serialized write sequencing via a per-instance `writeBarrier: AtomicReference<CompletableDeferred<Unit>>`. Each new write operation, from either `.apply()` or `.commit()`, will now:
- Wait for the previous write to complete (`previousWriteBarrier.await()`).
- Perform the write under `writeMutex` to ensure mutual exclusion.
- Complete its own barrier, unblocking the next writer in the queue.
This guarantees that apply and commit operations are …
> fix: Serialize entry writes

- CHANGELOG.md
- README.md
- safebox/build.gradle.kts
- safebox/src/androidTest/java/com/harrytmthy/safebox/SafeBoxTest.kt
- safebox/src/main/java/com/harrytmthy/safebox/SafeBox.kt
- safebox/src/main/java/com/harrytmthy/safebox/state/SafeBoxStateManager.kt
Synchronize `main` with the finalized `v1.1.3` release branch. The `v1.1.3` tag has already been created and published from `release/v1.1.3`. This PR forward-merges those changes back into `main` to keep history consistent.
> Forward-merge: release/v1.1.3 → main

- CHANGELOG.md
- README.md
- safebox/build.gradle.kts
This release introduces `v1.2.0-alpha01`, focusing on single-instance behavior and ergonomic access.
- **Single instance per filename**  
`SafeBox.create(...)` is idempotent and now atomic under concurrency.
- **New getter APIs**  
`SafeBox.get(fileName)` / `getOrNull(fileName)` enable retrieval without a `Context`.
- **Stability roll-up**  
Includes fixes from 1.1.1–1.1.3 (e.g. serialized writes to avoid overlapping `.apply()`/`.commit()`).
- **Developer experience**  
Gradle caching improvements for CI and KDoc/README refresh.  
Namespace note: `io.github.harrytmthy-dev` → `io.github.harrytmthy`.
- Repeated `create(...)` returns the same instance for a given filename.
- `close()` and `closeWhenIdle()` are deprecated and act as no-ops.
> release: v1.2.0-alpha01 with improved performance, stability, and new getter APIs

- safebox/src/main/AndroidManifest.xml
- safebox/src/main/java/com/harrytmthy/safebox/cryptography/ChaCha20CipherProvider.kt
- safebox/src/main/java/com/harrytmthy/safebox/startup/SafeBoxStartupProvider.kt
Reduce first-use latency by pre-warming the BouncyCastle at process start.
- Add `SafeBoxStartupProvider` that asynchronously touches `Cipher.getInstance("ChaCha20-Poly1305", "BC")` on startup to warm JCA/BC.
- Make `cipherPool` in ChaCha20CipherProvider **lazy**.
- No public API changes.
Closes #69
> feat(startup): Add SafeBoxStartupProvider to pre-warm BouncyCastle

- safebox/src/main/java/com/harrytmthy/safebox/SafeBox.kt
- safebox/src/main/java/com/harrytmthy/safebox/keystore/SecureRandomKeyProvider.kt
- safebox/src/main/java/com/harrytmthy/safebox/state/SafeBoxStateManager.kt
Introduce a read barrier to ensure SafeBox getters block until the initial hydration completes, matching `SharedPreferences` semantics.
- Added `awaitInitialReadBlocking()` in `SafeBoxStateManager` to synchronously await the initial read if not yet complete.
- Updated all `getXxx()` and `getAll()` accessors to invoke this barrier before returning values.
Closes #71
> feat: Add initial read barrier to align with SharedPreferences semantics

- safebox/src/main/java/com/harrytmthy/safebox/SafeBox.kt
- safebox/src/main/java/com/harrytmthy/safebox/storage/SafeBoxBlobStore.kt
Simplify the storage layer by removing unused initial-load strategy logic from `SafeBoxBlobStore`.
- Removed `initialLoadCompleted`, `initialLoadStrategy`, and `checkInitialLoad()` from `SafeBoxBlobStore`.
- Deprecated `SafeBox.setInitialLoadStrategy(...)` as a no-op since SafeBox now gates reads/writes internally.
- Retained `writeMutex` for internal safety.
Closes #68
> chore(storage): Remove initial-load strategy and stale checks from SafeBoxBlobStore

- safebox/src/androidTest/java/com/harrytmthy/safebox/SafeBoxTest.kt
- safebox/src/androidTest/java/com/harrytmthy/safebox/cryptography/ChaCha20CipherProviderTest.kt
- safebox/src/androidTest/java/com/harrytmthy/safebox/keystore/SecureRandomKeyProviderTest.kt
- safebox/src/main/java/com/harrytmthy/safebox/SafeBox.kt
- safebox/src/main/java/com/harrytmthy/safebox/cryptography/AesGcmCipherProvider.kt
- safebox/src/main/java/com/harrytmthy/safebox/cryptography/CipherProvider.kt
- safebox/src/main/java/com/harrytmthy/safebox/keystore/AndroidKeyStoreKeyProvider.kt
- safebox/src/main/java/com/harrytmthy/safebox/keystore/KeyProvider.kt
- safebox/src/main/java/com/harrytmthy/safebox/keystore/SafeSecretKey.kt
- safebox/src/main/java/com/harrytmthy/safebox/keystore/SecureRandomKeyProvider.kt
The overall fix consists of 2 parts:
- **Handling**
- On AEAD failures, `tryDecrypt()` schedules `scanAndRemoveDeadEntries()` to purge dead entries safely.
- **Prevention**
- One-time DEK rewrap to the default KEK alias when a legacy alias exists.
- Wrapped DEK file redirected from `$keyAlias.bin` to `$fileName.key.bin` with atomic persistence.
- AAD fixed to `fileName.toByteArray()`; deprecate AAD-taking `create(...)` overload.
- **AndroidKeyStoreKeyProvider**
- `shouldRotateKey()` is true if default alias is missing or legacy alias exists.
- `rotateKey()` provisions default alias and deletes the legacy alias to mark migration complete.
- **AesGcmCipherProvider**
- Forwards `rotateKey()` and `shouldRotateKey()` to the underlying `KeyProvider`.
- **SecureRandomKeyProvider**
- Rewrap in …
> fix: Handle & prevent unintentional KEK rotation and dead entries

- safebox/src/androidTest/java/com/harrytmthy/safebox/SafeBoxTest.kt
- safebox/src/main/java/com/harrytmthy/safebox/SafeBox.kt
Fix stale `clear()` flag when reusing `SharedPreferences.Editor`. Preserving an editor instance after calling `clear()` caused unintended full wipes on subsequent `commit()`/`apply()` calls.
- Replace `cleared.get()` with `cleared.getAndSet(false)`.
- Add a test to cover the edge case.
Closes #86
> fix(editor): Reset cleared flag after commit/apply

- safebox/src/androidTest/java/com/harrytmthy/safebox/SafeBoxTest.kt
- safebox/src/main/java/com/harrytmthy/safebox/cryptography/ChaCha20CipherProvider.kt
Replace the per-instance cipher lock with a process-wide mutex in `ChaCha20CipherProvider` to stop `AEADBadTagException` under concurrent `apply()` and read workloads.
- Added a single static lock inside `ChaCha20CipherProvider` and guard both `encrypt` and `decrypt`.
- Verified with the flood-apply test and a read assertion loop. No AEAD errors.
Closes #90
> fix(crypto): Prevent AEADBadTagException via a process-wide mutex

- safebox/src/androidTest/java/com/harrytmthy/safebox/SafeBoxTest.kt
- safebox/src/main/java/com/harrytmthy/safebox/SafeBox.kt
- safebox/src/main/java/com/harrytmthy/safebox/engine/SafeBoxEngine.kt
Skip no-op batches, shorten critical sections around `updateEntries`, and gate clear-path notifications behind the presence of a listener callback.
Closes #92
> perf(engine): Improve engine write performance by shrinking critical update paths

- CHANGELOG.md
- README.md
- safebox/build.gradle.kts
This PR finalizes the v1.2.0 release of SafeBox. The update delivers centralized runtime orchestration, faster write paths, and stable cryptography under concurrency. Documentation and benchmarks are refreshed.
---
- **SafeBoxEngine:** Owns in-memory entries, the initial-load barrier, write sequencing, and AEAD dead-entry purge. Also triggers per-key change notifications. ([#84](https://github.com/harrytmthy/safebox/issues/84), [#82](https://github.com/harrytmthy/safebox/issues/82))
- **ChaCha20-Poly1305 mutex:** Guarded by a process-wide lock to prevent AEADBadTagException under mixed read and write workloads. ([#90](https://github.com/harrytmthy/safebox/issues/90))
- **Faster engine writes:** Smaller critical sections and reduced lock contention during bursty apply or commit. …
> release: v1.2.0 with SafeBoxEngine, faster writes, and concurrency-stable crypto

- safebox/src/main/java/com/harrytmthy/safebox/SafeBox.kt
- safebox/src/main/java/com/harrytmthy/safebox/decoder/ByteDecoder.kt
- safebox/src/main/java/com/harrytmthy/safebox/engine/SafeBoxEngine.kt
- safebox/src/test/java/com/harrytmthy/safebox/extensions/ByteExtensionsTest.kt
Move `castFailureStrategy` into `ByteDecoder`, add a setter, and delegate updates through `SafeBoxEngine`. Remove the unnecessary `AtomicReference` from `SafeBox` and keep the existing public method delegating internally.
Closes #98
> refactor(decoder): Transfer castFailureStrategy ownership to ByteDecoder

- safebox/src/androidTest/java/com/harrytmthy/safebox/SafeBoxTest.kt
- safebox/src/main/java/com/harrytmthy/safebox/SafeBox.kt
- safebox/src/main/java/com/harrytmthy/safebox/engine/SafeBoxEngine.kt
Bring SafeBox change notifications in line with platform `SharedPreferences`.
Closes #102
> fix: Match SharedPreferences listener semantics

- safebox/src/androidTest/java/com/harrytmthy/safebox/SafeBoxTest.kt
- safebox/src/androidTest/java/com/harrytmthy/safebox/cryptography/AesGcmCipherProviderTest.kt
- safebox/src/androidTest/java/com/harrytmthy/safebox/cryptography/ChaCha20CipherProviderTest.kt
- safebox/src/androidTest/java/com/harrytmthy/safebox/keystore/SecureRandomKeyProviderTest.kt
- safebox/src/main/java/com/harrytmthy/safebox/SafeBox.kt
- safebox/src/main/java/com/harrytmthy/safebox/cryptography/AesGcmCipherProvider.kt
- safebox/src/main/java/com/harrytmthy/safebox/engine/SafeBoxEngine.kt
- safebox/src/main/java/com/harrytmthy/safebox/keystore/SecureRandomKeyProvider.kt
Drop deprecated alias parameters from public APIs and wire SafeBox to the alias-less crypto factory. This finalizes the direction from #103 and fits the split from #110.
- Remove `SafeBox.create(context, fileName, keyAlias, valueKeyStoreAlias, ...)`.
- Preserve internal migration from legacy alias files/keystore.
- Update unit/instrumented tests and KDoc.
Closes #111
> refactor: Remove alias-based fields

- safebox/src/androidTest/java/com/harrytmthy/safebox/SafeBoxTest.kt
- safebox/src/androidTest/java/com/harrytmthy/safebox/keystore/AndroidKeyStoreKeyProviderTest.kt
- safebox/src/main/java/com/harrytmthy/safebox/cryptography/AesGcmCipherProvider.kt
- safebox/src/main/java/com/harrytmthy/safebox/cryptography/ChaCha20CipherProvider.kt
- safebox/src/main/java/com/harrytmthy/safebox/cryptography/CipherProvider.kt
- safebox/src/main/java/com/harrytmthy/safebox/keystore/AndroidKeyStoreKeyProvider.kt
- safebox/src/main/java/com/harrytmthy/safebox/keystore/KeyProvider.kt
- safebox/src/main/java/com/harrytmthy/safebox/keystore/SecureRandomKeyProvider.kt
Finish removing alias-based and rotation-specific code paths and simplify the crypto/keystore surface to match the new alias-less design.
Closes #111
> refactor: Clean up alias-based fields leftovers and KEK migration

- safebox-crypto/src/main/java/com/harrytmthy/safebox/keystore/AndroidKeyStoreKeyProvider.kt
- safebox-crypto/src/main/java/com/harrytmthy/safebox/keystore/SecureRandomKeyProvider.kt
- safebox/src/androidTest/java/com/harrytmthy/safebox/SafeBoxTest.kt
- safebox/src/androidTest/java/com/harrytmthy/safebox/migration/SafeBoxMigrationHelperTest.kt
Initialize the DEK from disk lazily and guard the first write with a **per-file (by `fileName`) lock** so both providers resolve to the same key. Prevents divergent DEKs and preserves persistence across restarts.
Closes #119
> fix(keystore): Ensure single DEK per file via lazy on-disk init & per-file lock

- CHANGELOG.md
- README.md
- docs/OBSERVABILITY.md
- safebox/build.gradle.kts
This release introduces `v1.3.0-alpha01`, focusing on a standalone crypto module, API simplification, and size/perf wins.
- **New `:safebox-crypto` module** for reuse beyond preferences. ([#110])
- **SafeBoxCrypto helper** with URL-safe Base64 strings. ([#121])
- **API cleanup** by removing alias-based params from public APIs. ([#111])
- **APK size** cut by replacing `bcprov-jdk15to18` and using targeted keep rules. ([#115])
- **Lower contention** by isolating ChaCha providers and ensuring one DEK per file via per-file locks. ([#117], [#119])
- **CI** improvements by streamlining Gradle caching and concurrency. ([#108])
- Removed alias-based creation. If you relied on custom `valueKeyStoreAlias`, migrate data first. ([#103], [#111])
> release: v1.3.0-alpha01 with crypto module, API cleanup, and perf gains

- safebox/src/main/java/com/harrytmthy/safebox/state/SafeBoxGlobalStateObserver.kt
- safebox/src/main/java/com/harrytmthy/safebox/state/SafeBoxState.kt
- safebox/src/main/java/com/harrytmthy/safebox/state/SafeBoxStateListener.kt
- Marked `SafeBoxState`, `SafeBoxStateListener`, and `SafeBoxGlobalStateObserver` as `@Deprecated` with clear KDoc explaining why and removal target (v1.4).
- Kept behavior unchanged in 1.3.x (no runtime changes).
- Updated inline docs to recommend relying on `SharedPreferences` listener patterns and not on SafeBox-specific state.
Closes #125
> docs(state): Deprecate state, state listener, and global state listener

- scripts/pre-push
Add `apiCheck` to the pre-push hook and standardize failure messages. This prevents accidental public API changes from being pushed.
Closes #131
> chore: Add apiCheck to pre-push hook

- safebox/src/androidTest/java/com/harrytmthy/safebox/storage/SafeBoxBlobStoreTest.kt
- safebox/src/main/java/com/harrytmthy/safebox/storage/SafeBoxBlobStore.kt
Adjust page-fit bounds and entry-size validation in the blob store, and add paging unit tests.
Closes #139
> fix(storage): Adjust page bounds & add unit tests

- README.md
Improve the "Why SafeBox?" section in `README.md` to make it more readable and developer-friendly.
Closes #146
> docs(readme): Improve clarity in Why SafeBox section
